name: Build App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
